import React from 'react'

const Chat = () => {
  return (
    <>
        <h1>Chat Here</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio harum commodi quibusdam nostrum aut qui, natus nulla vitae itaque, aliquid blanditiis. Sapiente quaerat velit ab natus at assumenda similique. Quis, qui tenetur. Eligendi illo nisi, cumque dolore eveniet incidunt ratione fugiat quo. Ipsa id aliquam maxime autem perspiciatis fugit iusto dolorum laboriosam nesciunt dolores adipisci, laborum voluptates quaerat! Dicta sit, corrupti autem dolores doloribus quae cum mollitia, vitae, doloremque animi incidunt odio perspiciatis labore quod similique consequuntur odit! Cumque sed ullam blanditiis neque fugiat in ad optio doloremque, illo cum possimus adipisci corporis accusamus! Magni illo dignissimos reiciendis eveniet molestias!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio harum commodi quibusdam nostrum aut qui, natus nulla vitae itaque, aliquid blanditiis. Sapiente quaerat velit ab natus at assumenda similique. Quis, qui tenetur. Eligendi illo nisi, cumque dolore eveniet incidunt ratione fugiat quo. Ipsa id aliquam maxime autem perspiciatis fugit iusto dolorum laboriosam nesciunt dolores adipisci, laborum voluptates quaerat! Dicta sit, corrupti autem dolores doloribus quae cum mollitia, vitae, doloremque animi incidunt odio perspiciatis labore quod similique consequuntur odit! Cumque sed ullam blanditiis neque fugiat in ad optio doloremque, illo cum possimus adipisci corporis accusamus! Magni illo dignissimos reiciendis eveniet molestias!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio harum commodi quibusdam nostrum aut qui, natus nulla vitae itaque, aliquid blanditiis. Sapiente quaerat velit ab natus at assumenda similique. Quis, qui tenetur. Eligendi illo nisi, cumque dolore eveniet incidunt ratione fugiat quo. Ipsa id aliquam maxime autem perspiciatis fugit iusto dolorum laboriosam nesciunt dolores adipisci, laborum voluptates quaerat! Dicta sit, corrupti autem dolores doloribus quae cum mollitia, vitae, doloremque animi incidunt odio perspiciatis labore quod similique consequuntur odit! Cumque sed ullam blanditiis neque fugiat in ad optio doloremque, illo cum possimus adipisci corporis accusamus! Magni illo dignissimos reiciendis eveniet molestias!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio harum commodi quibusdam nostrum aut qui, natus nulla vitae itaque, aliquid blanditiis. Sapiente quaerat velit ab natus at assumenda similique. Quis, qui tenetur. Eligendi illo nisi, cumque dolore eveniet incidunt ratione fugiat quo. Ipsa id aliquam maxime autem perspiciatis fugit iusto dolorum laboriosam nesciunt dolores adipisci, laborum voluptates quaerat! Dicta sit, corrupti autem dolores doloribus quae cum mollitia, vitae, doloremque animi incidunt odio perspiciatis labore quod similique consequuntur odit! Cumque sed ullam blanditiis neque fugiat in ad optio doloremque, illo cum possimus adipisci corporis accusamus! Magni illo dignissimos reiciendis eveniet molestias!</p>
    </>
  )
}

export default Chat
